# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://urbanclimate.be/"
title: LEGO Urban planner
# copyright: "© [PaperMod Contributors](https://github.com/adityatelange/hugo-PaperMod/graphs/contributors)"
paginate: 5
theme: [PaperMod]

# enableInlineShortcodes: true
enableRobotsTXT: true
# buildDrafts: false
# buildFuture: false
# buildExpired: false
# enableEmoji: true
# pygmentsUseClasses: true
# mainsections: ["posts", "papermod"]

# minify:
#   disableXML: true
#   # minifyOutput: true

DefaultContentLanguage: "nl"
languages:
  nl:
    languageName: "Nederlands"
    weight: 1
    params:
      homeInfoParams:
        Title: "Wat is de LEGO urban climate game?"
        Content: >
          ![](/assets/images/homepage.jpeg)

          Je hebt het vast al gemerkt: het klimaat verandert! Extreem weer zoals hittegolven worden steeds heviger en komen vaker voor. Tijdens de zomer kunnen die hittegolven leiden tot een hogere temperatuur in steden ten opzichte van het platteland. Dit wordt het stedelijk hitte-eiland of urban heat island effect genoemd. Kortweg: tussen al het beton en de asfalt voel je de hitte des te meer, zeker 's nachts! Deze hoge temperatuur en hittestress kan leiden tot gezondheidsproblemen. Maar wat zou er gebeuren mochten we alle parkings ombouwen tot parken?


          Met de LEGO urban climate game ben jij de architect van de toekomst. Bouw je miniatuurstad met LEGO, en met behulp van artificiële intelligentie zie je meteen de impact van gebouwen, groen en water op de temperatuur. Kun jij je buurt klimaatresistent maken?
    menu:
      main:
        - name: Zoeken
          url: search/
          weight: 95
        - name: Archief
          url: archive/
          weight: 99
        - name: Tags
          url: tags/
          weight: 99

  fr:
    languageName: "Français"
    weight: 2
    params:
      homeInfoParams:
        Title: "Qu'est-ce que le *LEGO urban climate game* ?"
        Content: >
          ![](/assets/images/homepage.jpeg)

          Vous l'avez probablement déjà remarqué : le climat change ! Les conditions météorologiques extrêmes telles que les vagues de chaleur deviennent plus graves et plus fréquentes. Pendant l'été, ces vagues de chaleur peuvent entraîner des températures plus élevées dans les villes par rapport aux zones rurales. C'est ce qu'on appelle l'effet d'îlot de chaleur urbain. Bref : entre tout le béton et l'asphalte on ressent d'autant plus la chaleur, surtout la nuit ! Cette température élevée et le stress thermique peuvent entraîner des problèmes de santé. Mais que se passerait-il si nous convertissions tous les parkings en parcs ?


          Avec le LEGO urban climate game, vous êtes l'architecte du futur. Construisez votre ville miniature avec des LEGO, et avec l'aide de l'intelligence artificielle, vous pouvez immédiatement voir l'impact des bâtiments, de la verdure et de l'eau sur la température. Pouvez-vous rendre votre quartier résistant au climat ?
    menu:
      main:
        - name: Recherche
          url: search/
          weight: 95
        - name: Archive
          url: archive/
          weight: 99
        - name: Tags
          url: tags/
          weight: 99

  en:
    languageName: "English"
    weight: 3
    params:
      homeInfoParams:
        Title: "What is the LEGO urban climate game?"
        Content: >
          ![](/assets/images/homepage.jpeg)

          You've probably already noticed: our climate is changing! Extreme weather such as heat waves become more severe and more frequent. During summer, these heat waves can lead to higher temperatures in cities compared to rural areas. This is called the urban heat island effect. In short, between the concrete and the asphalt you feel the heat more, especially at night! High temperatures and heat stress can lead to health problems. But what would happen if we converted all the car parks into parks?


          With the LEGO urban climate game, you are the architect of the future. Build your miniature city with LEGO, and with the help of artificial intelligence, you can immediately see the impact of buildings, greenspace and water on the temperature. Can you make your neighbourhood climate-resistant?
    menu:
      main:
        - name: Search
          url: search/
          weight: 95
        - name: Archive
          url: archive/
          weight: 99
        - name: Tags
          url: tags/
          weight: 99

#     # custom params for each language should be under [langcode].parms - hugo v0.120.0
#     params:
#       languageAltTitle: French
#       profileMode:
#         enabled: true
#         title: PaperMod
#         imageUrl: "https://raw.githubusercontent.com/googlefonts/noto-emoji/master/svg/emoji_u1f9d1_1f3fb_200d_1f4bb.svg"
#         imageTitle: ProfileMode image
#         # imageWidth: 120
#         # imageHeight: 120
#         subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
#         buttons:
#           - name: Blog
#             url: posts
#           - name: Profile Mode
#             url: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

params:
  ShowShareButtons: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true

#  socialIcons:
#    - name: github
#      title: View Source on Github
#      url: "https://github.com/adityatelange/hugo-PaperMod"
#     - name: Discord
#       title: Join discord community
#       url: "https://discord.gg/ahpmTvhVmp"
#     - name: X
#       title: Share PaperMod on X/Twitter
#       url: "https://x.com/intent/tweet/?text=Checkout%20Hugo%20PaperMod%20%E2%9C%A8%0AA%20fast,%20clean,%20responsive%20Hugo%20theme.&url=https://github.com/adityatelange/hugo-PaperMod&hashtags=Hugo,PaperMod"
#     - name: KoFi
#       title: Buy me a Ko-Fi :)
#       url: "https://ko-fi.com/adityatelange"

  editPost:
    URL: "https://github.com/ladc/urbanclimate-website/tree/master/content"
    # Text: "Suggest Changes"
    appendFilePath: true
